How to contribute guide
ACCESS-NRI-Community/ACCESSHub pull request #12
Opened 2022-09-02 04:07 UTC by ccarouge

Closes #1.

If you want to locally preview the changes for the review:
1. Install Material for Mkdocs: `pip install mkdocs-material` or `conda create -n doc -c conda-forge mkdocs-material`
2. In a terminal in your ACCESSHub local repo, run `mkdocs serve`
It will build the site on a server and give you the URL. It can live update on save if you need to. 

All this is in the How to contribute guide but I thought that'd be faster for you.

2022-09-02 04:08 UTC, aidanheerdegen commented
Should I try the solution in #11 in case it changes this?

2022-09-02 04:11 UTC, ccarouge commented
Sure go for it. I'll put #11 as a blocker so we know when to put this in review.

2022-09-02 04:13 UTC, aidanheerdegen commented
Nice.

2022-09-04 23:41 UTC, ccarouge commented
@aidanheerdegen I have rebased this work on `main` to use the PR preview workflow, but the preview is broken. The workflow says it worked fine but the result is not good. Locally, `mkdocs` builds the documentation fine after the rebase. Any idea?

2022-09-04 23:48 UTC, aidanheerdegen commented
Preview is fine for me. When I was trialling the preview stuff I checked it before it was finished rendering, and it was weird, like massive icons and some rubbish at the bottom, which is what you get if you use a non-existent directory location, e.g.

https://access-nri-community.github.io/ACCESSHub/lalala/

Try reloading the preview and see if it looks ok for you.

This is clearly something we need to warn people about in the How-To (which is looking great BTW)

2022-09-05 00:07 UTC, ccarouge commented
That was it. 
I'll add to the How to about the preview on PR and the delay.

2022-09-05 04:04 UTC, aidanheerdegen requested changes
Looks good. Just some suggestions to clarify some sections.

2022-09-05 04:04 UTC, aidanheerdegen commented on docs/Help/change_navigation.md
> +It is possible to define several sections per tab. For example:
"It is possible to define several sections per tab by using more levels of indentation"

2022-09-05 04:54 UTC, rbeucher requested changes
I think it's OK but I would not go too much in details on how to do things locally.
I would recommend using GitHub.
I think people who are more likely do to it locally already know how to do it...
The less text, the better...

2022-09-05 04:54 UTC, rbeucher commented on docs/Help/change_navigation.md
> +The filenames indicate the path to the file with the text for each page. It is recommended to use the title of each file (i.e. the Header 1) as the name of the page and the filename.
You can just say that all the paths are relative to the `docs` directory

2022-09-05 04:54 UTC, rbeucher commented on docs/Help/modify_documentation.md
> +## Edit directly on GitHub
I would recommend this. People who know how to use GitHub don't really need explanation so I am wondering if the next session is really useful...

2022-09-05 04:54 UTC, rbeucher commented on docs/Help/modify_documentation.md
> +In the pull request description, make sure to add the text `Closes #X` where X is the Issue number associated with your modifications so that the Issue and the pull request are linked, cross-referenc
A lot of the PR process could be streamlined using a PR template where we explain what needs to be done:
Select a reviewer etc...

Also it might be good to ask people to prefix the PR with "Draft" if it is work in progress..

Finally, we need to create a bunch of tags on GitHub so we can prioritize things and facilitate triage.

2022-09-05 04:56 UTC, ccarouge commented on docs/Help/contribution_setup.md
> +## Install Material for Mkdocs (recommended)
Done in https://github.com/ACCESS-NRI-Community/ACCESSHub/pull/12/commits/d54baa5af13a519d5d0bc0ab5a3b0df675ac4478

2022-09-05 04:56 UTC, ccarouge commented on docs/Help/modify_documentation.md
> +For all additions or modifications to the ACCESSHub site, it is recommended to start by opening an [Issue](https://github.com/ACCESS-NRI-Community/ACCESSHub/issues) in the ACCESSHub GitHub repository
Done in https://github.com/ACCESS-NRI-Community/ACCESSHub/commit/d54baa5af13a519d5d0bc0ab5a3b0df675ac4478

2022-09-05 04:56 UTC, ccarouge commented on docs/Help/modify_documentation.md
> +    If you have installed mkdocs-material via conda, make sure you activate the correct environment first
Done in https://github.com/ACCESS-NRI-Community/ACCESSHub/commit/d54baa5af13a519d5d0bc0ab5a3b0df675ac4478

2022-09-05 04:56 UTC, ccarouge commented on docs/Help/modify_documentation.md
> +Once you are satisfy with your modifications, you will need to:
Done in https://github.com/ACCESS-NRI-Community/ACCESSHub/commit/d54baa5af13a519d5d0bc0ab5a3b0df675ac4478

2022-09-05 04:58 UTC, ccarouge commented on docs/Help/modify_documentation.md
> +In the pull request description, make sure to add the text `Closes #X` where X is the Issue number associated with your modifications so that the Issue and the pull request are linked, cross-referenc
Aidan's changes are done in https://github.com/ACCESS-NRI-Community/ACCESSHub/commit/d54baa5af13a519d5d0bc0ab5a3b0df675ac4478

Should we put creating a PR template in To Do which would mean leave this as is for now or solve this now?

2022-09-05 04:58 UTC, ccarouge commented on docs/Help/change_navigation.md
> +The navigation for the site is defined in `mkdocs.yml`.
Done in https://github.com/ACCESS-NRI-Community/ACCESSHub/commit/d54baa5af13a519d5d0bc0ab5a3b0df675ac4478

2022-09-05 04:58 UTC, ccarouge commented on docs/Help/change_navigation.md
> +The filenames indicate the path to the file with the text for each page. It is recommended to use the title of each file (i.e. the Header 1) as the name of the page and the filename.
Done in https://github.com/ACCESS-NRI-Community/ACCESSHub/commit/d54baa5af13a519d5d0bc0ab5a3b0df675ac4478

2022-09-05 05:01 UTC, ccarouge commented on docs/Help/modify_documentation.md
> +## Edit directly on GitHub
I was thinking all the stuff about using GitHub which is the bit about doing it locally should go in a "How to use GitHub" resource/documentation page as that will be needed for everything and not just the Hub. But we don't have that yet... 

I don't like recommending editing on GitHub directly, at least at the start as I imagine some submissions might be heavy with modifications to the navigation. But I'm happy to remove the details on how to use GitHub from the section on Editing locally.

2022-09-05 05:25 UTC, ccarouge commented on docs/Help/change_navigation.md
> +It is possible to define several sections per tab. For example:
done in https://github.com/ACCESS-NRI-Community/ACCESSHub/commit/d54baa5af13a519d5d0bc0ab5a3b0df675ac4478

2022-09-05 05:36 UTC, rbeucher approved these changes

2022-09-05 05:41 UTC, aidanheerdegen commented on docs/Help/modify_documentation.md
> +In the pull request description, make sure to add the text `Closes #X` where X is the Issue number associated with your modifications so that the Issue and the pull request are linked, cross-referenc
Make it a To Do and get this merged I reckon.

2022-09-05 05:42 UTC, aidanheerdegen approved these changes

2022-09-05 06:12 UTC, ccarouge commented on docs/Help/modify_documentation.md
> +## Edit directly on GitHub
I've put the details in a separate section so it can serve as a start of a How to work with GitHub documentation. Done in https://github.com/ACCESS-NRI-Community/ACCESSHub/pull/12/commits/0b9b9f539fa0d466dd5b1ba83e839455585660f5

2022-09-05 06:14 UTC, merged